["What is your relationship status?",
 "What is your gender?",
 "What genders are you open to living with?",
 "Not open to living with a particular gender?",
 "OK with what ages of roommate?",
 "Do you have kids?",
 "How many kids?",
 "What ages?",
 "What is your education level?",
 "Do you smoke tobacco?",
 "Do you smoke marijuana?",
 "Do you use any other drugs aside from tobacco and marijuana?",
 "What drugs are you open to your roommate using? Pick from list",
 "Do you drink alcohol?",
 "How often do you drink alcohol?",
 "Do you have pets or emotional support animals?",
 "What kind of pets/support animals?",
 "Are you open to a roommate who has a pet or emotional support animal?",
 "Do you have any allergies?",
 "What ethnicity describes you?",
 "Do you belong to a particular religion?",
 "Do you consider yourself carefree or intense?",
 "What is the importance of religion/God/spirituality in your life?",
 "Do you enjoy politics?",
 "Where are you on political spectrum?",
 "Consider yourself normal or weird?",
 "How often do you clean your space?",
 "How important is cleanliness to you?",
 "Are you currently employed?",
 "Do you work from home?",
 "Do you work nights?",
 "If you are unemployed, do you plan on working?",
 "Do you recycle?",
 "How long before you wash the dishes?",
 "How do you feel about living with someone who is messy?",
 "Do you like movies?",
 "Do you like sports?",
 "Are you a creative type/artist/musician/writer?",
 "Would you date someone who does drugs?",
 "Do you speak a second language? Which?",
 "What SPAs are you willing to live in?",
 "Any neighborhood you are unwilling to live in?",
 "What cultural background of roommate are you open to?",
 "Do you prefer it cold or hot in your living space?",
 "When do you pay bills? Early, right on time, often late?",
 "Do you like having friends or family over to the house?",
 "Do you plan on having anyone spend the night at your place?",
 "As long as agreements are made about frequency and access to common space,
 are,
 you ok with your roommate having friends spend the night?",
 "Do you consider yourself a home body or do you like to go out?",
 "Would guns or weapons be allowed in the house as long as they are legally,
 owned and away from children?",
 "What is your income?",
 "How much income do you think you could reasonably make in the next 6 months?",
 "Do you consider yourself a morning person or a night owl?",
 "Do you have eviction(s)?",
 "Do you consider yourself loud or quiet?",
 "What about the environment you prefer to live in? Loud or quiet?",
 "If you have children, do you think its ok to spank as a form of discipline?",
 "Is it ok for others who you trust to discipline your children?",
 "Have you ever had a roommate?",
 "Have you ever lived on your own?",
 "Do you owe utility arrears?",
 "Are you open to borrowing/lending money?",
 "Are you open to borrowing/lending food?",
 "Are you affiliated with any gangs?",
 "Do you have any ongoing legal issues?"]
